Repository nextcloud/files_downloadlimit, pull requests merged in 2024-03, with the labels that each got.

#224 feat: Support Nextcloud 29
  appinfo/info.xml
  appinfo/routes.php
Labels: 3. to review

#225 refactor: Remove deprecated code and refactor
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/ShareLinkAccessedListener.php
Labels: 3. to review

#226 feat: Register new download limit entry
  .eslintrc.js
  package-lock.json
  package.json
  src/actions/DownloadLimitAction.ts
  src/components/DownloadLimitEntry.vue
  src/logger.ts
  src/main.js
  src/main.ts
  src/models/DownloadLimitAction.js
  src/models/LimitEnableAction.js
  src/services/DownloadLimitService.ts
Labels: 3. to review

#213 Update npm and node engines versions
  package.json
Labels: dependencies

#227 refactor: Move public script to TypeScript
  src/public.js
  src/public.ts
Labels: 3. to review

#228 chore: Build with vite
  .eslintrc.cjs
  .gitignore
  babel.config.js
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/LoadSidebarListener.php
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
  webpack.js
Labels: 3. to review

#230 fix: Update limit via event listener
  src/components/DownloadLimitEntry.vue
Labels: 3. to review

#231 chore: Commit assets to source control
  .gitignore
  css/files_downloadlimit-main.css
  css/files_downloadlimit-public.css
  js/files_downloadlimit-main.mjs
  js/files_downloadlimit-main.mjs.map
  js/files_downloadlimit-public.mjs
  js/files_downloadlimit-public.mjs.map
  js/logger-DZIvzaVr.mjs
  js/logger-DZIvzaVr.mjs.map
  js/vendor.LICENSE.txt
Labels: 3. to review

#209 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/pr-feedback.yml
Labels: dependencies, 3. to review, automated

#234 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
Labels: dependencies, 3. to review, automated

#238 chore: Add README and document API
  README.md
  appinfo/info.xml
Labels: 3. to review

#237 chore: Add some workflows from upstream
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  .gitignore
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Db/Limit.php
  lib/Db/LimitMapper.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/LoadSidebarListener.php
  lib/Listener/ShareLinkAccessedListener.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review

#236 chore: Remove unnecessary workflows and update existing
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#246 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#248 [stable28] Fix npm audit
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  package-lock.json
Labels: dependencies, 3. to review

#240 docs: Add asserts for example responses
  README.md
  appinfo/info.xml
Labels: 3. to review

#249 chore: Disable ocp update for stable branches
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#241 feat: Provide limit via dav property
  README.md
  lib/AppInfo/Application.php
  lib/Dav/PropFindPlugin.php
  lib/LimitList.php
  lib/Listener/SabrePluginAddListener.php
  psalm.xml
  tests/psalm-baseline.xml
Labels: 3. to review

#250 feat: Support 28
  appinfo/info.xml
Labels: 3. to review

#253 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#254 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#257 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
