Repository nextcloud/files_downloadlimit, pull requests merged in 2024-08, with the labels that each got.

#328 fix: prevent null token
  lib/Listener/ShareLinkAccessedListener.php
Labels: bug, 3. to review

#319 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#331 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#341 chore: Fix composer configuration for OCP update
  composer.json
  composer.lock
  psalm.xml
Labels: 3. to review

#343 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#334 [stable28] Fix npm audit
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Db/Limit.php
  lib/Db/LimitMapper.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Listener/LoadSidebarListener.php
  lib/Listener/ShareLinkAccessedListener.php
  package-lock.json
Labels: dependencies, 3. to review

#332 [stable29] Update nextcloud/ocp dependency
  .github/workflows/appstore-build-publish.yml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/block-unconventional-commits.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#333 [stable29] Fix npm audit
  css/_plugin-vue2_normalizer-IjhRd8hy.chunk.css
  css/admin-C8PZeoZ1.chunk.css
  css/files_downloadlimit-admin.css
  css/files_downloadlimit-main.css
  css/files_downloadlimit-public.css
  css/main-BrixX9IR.chunk.css
  css/public-AYSbOwrg.chunk.css
  js/_plugin-vue2_normalizer-FUIjkb-y.chunk.mjs
  js/_plugin-vue2_normalizer-FUIjkb-y.chunk.mjs.map
  js/_plugin-vue2_normalizer.chunk.mjs
  js/_plugin-vue2_normalizer.chunk.mjs.map
  js/files_downloadlimit-admin.mjs
  js/files_downloadlimit-admin.mjs.map
  js/files_downloadlimit-main.mjs
  js/files_downloadlimit-main.mjs.map
  js/files_downloadlimit-public.mjs
  js/files_downloadlimit-public.mjs.map
  js/index-B5eY9Cro.chunk.mjs
  js/index-B5eY9Cro.chunk.mjs.map
  js/index.chunk.mjs
  js/index.chunk.mjs.map
  js/logger-BhVz1cYJ.chunk.mjs
  js/logger-BhVz1cYJ.chunk.mjs.map
  js/logger.chunk.mjs
  js/logger.chunk.mjs.map
  js/purify.es-FFFEAyv8.chunk.mjs
  js/purify.es-FFFEAyv8.chunk.mjs.map
  js/purify.es.chunk.mjs.map
  package-lock.json
Labels: dependencies, 3. to review

#346 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#347 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#359 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#354 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
