Repository nextcloud/files_downloadlimit, pull requests merged in 2025-09, with the labels that each got.

#516 feat(deps): Add Nextcloud 33 support
  .github/dependabot.yml
  .github/workflows/npm-audit-fix.yml
  appinfo/info.xml
  js/files_downloadlimit-admin.mjs.license
  js/files_downloadlimit-admin.mjs.map.license
  js/files_downloadlimit-main.mjs.license
  js/files_downloadlimit-main.mjs.map.license
  js/files_downloadlimit-public.mjs.license
  js/files_downloadlimit-public.mjs.map.license
  js/logger-DOtXxQhN.chunk.mjs.license
  js/logger-DOtXxQhN.chunk.mjs.map.license
  package-lock.json
  package.json
Labels: enhancement, 3. to review

#549 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#553 refactor: migrate to Vue 3
  css/_plugin-vue_export-helper-B6UFNITG.chunk.css
  css/admin-DikTc-Ns.chunk.css
  css/files_downloadlimit-admin.css
  css/files_downloadlimit-main.css
  eslint.config.js
  js/_plugin-vue2_normalizer-BdHTjQ9A.chunk.mjs
  js/_plugin-vue2_normalizer-BdHTjQ9A.chunk.mjs.map
  js/_plugin-vue_export-helper-DGKz3gaZ.chunk.mjs
  js/_plugin-vue_export-helper-DGKz3gaZ.chunk.mjs.license
  js/_plugin-vue_export-helper-DGKz3gaZ.chunk.mjs.map
  js/_plugin-vue_export-helper-DGKz3gaZ.chunk.mjs.map.license
  js/files_downloadlimit-admin.mjs
  js/files_downloadlimit-admin.mjs.license
  js/files_downloadlimit-admin.mjs.map
  js/files_downloadlimit-admin.mjs.map.license
  js/files_downloadlimit-main.mjs
  js/files_downloadlimit-main.mjs.license
  js/files_downloadlimit-main.mjs.map
  js/files_downloadlimit-main.mjs.map.license
  package-lock.json
  package.json
  src/admin.ts
  src/components/DownloadLimitEntry.vue
  src/main.ts
Labels: 3. to review
