Repository nextcloud/files_downloadlimit, pull requests merged in 2025-07, with the labels that each got.

#483 ci: update node.yml workflow from template
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
Labels: dependencies

#494 fix(public): use correct color for header text
  js/files_downloadlimit-public.mjs
  js/files_downloadlimit-public.mjs.map
  src/public.ts
Labels: bug, 3. to review, backport-request

#496 [stable31] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#503 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
